### ISSUE TITLE
Compilation error for contracts that compile with solc version 0.8.6

### ISSUE THREAD

**Issue by TilakMaddy** [smartcontractkit/ccip#807]
**Description**
Unable to compile contracts that should be able to compile with solc version 0.8.6.

I have grouped files in this repo by the solc compiler version that can be used to compile them using [graph resovlers](https://github.com/foundry-rs/compilers/blob/b16faac372bde7d74784ef3ec69f688be68e79ae/src/resolver/mod.rs#L307) of foundry-compilers backend.

Following groups were generated

1. Compiling 38 files with Solc 0.8.16+commit.07a7930e.Darwin.appleclang
2. Compiling 225 files with Solc 0.8.19+commit.7dd6d404.Darwin.appleclang
3. Compiling 316 files with Solc 0.8.25+commit.b61c2a91.Darwin.appleclang
4. Compiling 69 files with Solc 0.8.6+commit.11564f7e.Darwin.appleclang

I could compile the first 3 groups, but the last one failed with the Stack too deep error. (I have pasted the full message below)

**Basic Information**
Compiler error: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.

**Steps to Reproduce**

This is the solc command that I (my program) tried to run (inside the `ccip/contracts` folder with `solc` version 0.8.6)

```bash
/path/to/solc-0.8.6 --ast-compact-json ds-test/=foundry-lib/forge-std/lib/ds-test/src/ forge-std/=foundry-lib/forge-std/src/ @openzeppelin/=node_modules/@openzeppelin/ @arbitrum/=node_modules/@arbitrum/ hardhat/=node_modules/hardhat/ @eth-optimism/=node_modules/@eth-optimism/ @scroll-tech/=node_modules/@scroll-tech/ src/v0.8/ChainSpecificUtil_v0_8_6.sol src/v0.8/PermissionedForwardProxy.sol src/v0.8/automation/AutomationBase.sol src/v0.8/automation/ExecutionPrevention.sol src/v0.8/automation/HeartbeatRequester.sol src/v0.8/automation/KeeperBase.sol src/v0.8/automation/UpkeepFormat.sol src/v0.8/automation/interfaces/AutomationCompatibleInterface.sol src/v0.8/automation/interfaces/KeeperCompatibleInterface.sol src/v0.8/automation/interfaces/MigratableKeeperRegistryInterface.sol src/v0.8/automation/interfaces/MigratableKeeperRegistryInterfaceV2.sol src/v0.8/automation/interfaces/UpkeepTranscoderInterface.sol src/v0.8/automation/interfaces/UpkeepTranscoderInterfaceV2.sol src/v0.8/automation/interfaces/v1_2/AutomationRegistryInterface1_2.sol src/v0.8/automation/interfaces/v1_2/KeeperRegistryInterface1_2.sol src/v0.8/automation/interfaces/v1_3/AutomationRegistryInterface1_3.sol src/v0.8/automation/interfaces/v2_0/AutomationRegistryInterface2_0.sol src/v0.8/automation/libraries/external/Cron.sol src/v0.8/automation/libraries/internal/Cron.sol src/v0.8/automation/upkeeps/CronUpkeep.sol src/v0.8/automation/upkeeps/CronUpkeepDelegate.sol src/v0.8/automation/upkeeps/CronUpkeepFactory.sol src/v0.8/automation/upkeeps/EthBalanceMonitor.sol src/v0.8/automation/v1_2/KeeperRegistrar1_2.sol src/v0.8/automation/v1_2/KeeperRegistry1_2.sol src/v0.8/automation/v1_2/KeeperRegistryCheckUpkeepGasUsageWrapper1_2.sol src/v0.8/automation/v1_3/KeeperRegistry1_3.sol src/v0.8/automation/v1_3/KeeperRegistryBase1_3.sol src/v0.8/automation/v1_3/KeeperRegistryLogic1_3.sol src/v0.8/automation/v2_0/KeeperRegistrar2_0.sol src/v0.8/automation/v2_0/KeeperRegistry2_0.sol src/v0.8/automation/v2_0/KeeperRegistryBase2_0.sol src/v0.8/automation/v2_0/KeeperRegistryLogic2_0.sol src/v0.8/automation/v2_0/UpkeepTranscoder3_0.sol src/v0.8/interfaces/TypeAndVersionInterface.sol src/v0.8/shared/access/ConfirmedOwner.sol src/v0.8/shared/access/ConfirmedOwnerWithProposal.sol src/v0.8/shared/interfaces/AggregatorV3Interface.sol src/v0.8/shared/interfaces/IERC677Receiver.sol src/v0.8/shared/interfaces/IOwnable.sol src/v0.8/shared/interfaces/ITypeAndVersion.sol src/v0.8/shared/interfaces/LinkTokenInterface.sol src/v0.8/shared/ocr2/OCR2Abstract.sol src/v0.8/vrf/BatchVRFCoordinatorV2.sol src/v0.8/vrf/VRF.sol src/v0.8/vrf/VRFConsumerBaseV2.sol src/v0.8/vrf/VRFCoordinatorV2.sol src/v0.8/vrf/VRFTypes.sol src/v0.8/vrf/VRFV2Wrapper.sol src/v0.8/vrf/VRFV2WrapperConsumerBase.sol src/v0.8/vrf/dev/VRFSubscriptionBalanceMonitor.sol src/v0.8/vrf/interfaces/BlockhashStoreInterface.sol src/v0.8/vrf/interfaces/VRFCoordinatorV2Interface.sol src/v0.8/vrf/interfaces/VRFV2WrapperInterface.sol --allow-paths .
```

Is this expected and can we ignore it? or is there a fault in the compilation command?

**Additional Context**
We're doing this instead of forge build because we only want the AST `--ast-compact-json`. Although this is possible with `forge build --ast` it will take a lot of time because forge also has to generate bytecode

Project root -  `ccip/contracts`
Scope - `src/v0.8/`
Excluded - `tests/  test/ testhelpers/ lib/ node_modules/ mocks/ vendors/`

**Comment by TilakMaddy** [comment]
My guess is that since I am not sticking to any one foundry profile's scope I am getting this error. However, my doubt is that the depth of inline assembly doesn't depend on what is in scope. So ... I'm confused
